using MoneyBrain.Web.Application.Common.Interfaces;
using MoneyBrain.Web.Domain.Enums;

namespace MoneyBrain.Web.Domain.Entities;

/// <summary>
/// Transaction - belongs to exactly one account
/// </summary>
public class Transaction : IUserOwnedEntity
{
    public int Id { get; init; }
    
    public required string UserId { get; init; }
    
    public int AccountId { get; set; }
    
    public required DateTime Date { get; set; }
    
    /// <summary>
    /// Transaction amount (positive for income, negative for expense)
    /// </summary>
    public decimal Amount { get; set; }
    
    public int? PayeeId { get; set; }
    
    public int? CategoryId { get; set; }
    
    public string? Memo { get; set; }
    
    public TransactionStatus Status { get; set; } = TransactionStatus.Pending;
    
    /// <summary>
    /// Cleared flag (transaction has processed but not reconciled)
    /// </summary>
    public bool IsCleared { get; set; }
    
    /// <summary>
    /// Reconciled flag - reconciled transactions are immutable
    /// </summary>
    public bool IsReconciled { get; set; }
    
    /// <summary>
    /// Reconciliation session this transaction belongs to (if reconciled)
    /// </summary>
    public int? ReconciliationId { get; set; }
    
    /// <summary>
    /// Reference number (check number, confirmation, etc.)
    /// </summary>
    public string? ReferenceNumber { get; set; }
    
    /// <summary>
    /// Tags as comma-separated values
    /// </summary>
    public string? Tags { get; set; }
    
    /// <summary>
    /// If this transaction is part of a transfer, link to the other transaction
    /// </summary>
    public int? TransferTransactionId { get; set; }
    
    /// <summary>
    /// Whether this transaction recurs automatically.
    /// </summary>
    public bool IsRecurring { get; set; }
    
    /// <summary>
    /// Recurrence frequency (if IsRecurring is true).
    /// </summary>
    public RecurrenceFrequency? RecurrenceFrequency { get; set; }
    
    /// <summary>
    /// First date when this recurring transaction should appear.
    /// </summary>
    public DateTime? RecurrenceStartDate { get; set; }
    
    /// <summary>
    /// Next scheduled date for this recurring transaction (updated after each occurrence).
    /// </summary>
    public DateTime? NextRecurrenceDate { get; set; }
    
    /// <summary>
    /// If this transaction was auto-generated from a recurring template, this links to the template.
    /// </summary>
    public int? RecurringTemplateId { get; set; }

    /// <summary>
    /// If this transaction is a credit card bill, links to the credit card account.
    /// </summary>
    public int? CreditCardBillingSourceAccountId { get; set; }

    /// <summary>
    /// The billing cycle month this credit card bill represents (e.g., 2026-01 for January 2026).
    /// Format: YYYY-MM
    /// </summary>
    public string? BillingCycleMonth { get; set; }
    
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    
    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;
    
    // Navigation properties
    public Account Account { get; set; } = null!;
    
    public Payee? Payee { get; set; }
    
    public Category? Category { get; set; }
    
    public Reconciliation? Reconciliation { get; set; }
    
    public Transaction? TransferTransaction { get; set; }
    
    public Transaction? RecurringTemplate { get; set; }

    /// <summary>
    /// Navigation property for the credit card account this bill was generated from.
    /// </summary>
    public Account? CreditCardBillingSourceAccount { get; set; }
    
    public ICollection<TransactionSplit> Splits { get; set; } = [];
    
    /// <summary>
    /// Ledger entries generated by this transaction for double-entry bookkeeping.
    /// Every transaction should generate at least 2 entries (debit and credit).
    /// </summary>
    public ICollection<LedgerEntry> LedgerEntries { get; set; } = [];
}
